### PR TITLE
Select discography display mode if at least one item has an artwork

### PR DESCRIPTION
**Pull request by saecki**
Require only one item to have an artwork, instead of all of them, to select the discography display mode. Without this change the random albums for example would be set to the directories display mode if just one album art was missing.

### CODE REVIEW

**Comment by agersant** [comment]
I think we should add a placeholder for missing artwork, otherwise I worry the UI might be a little wonky.

**Comment by saecki** [comment]
This added a fallback artwork for the discography and now playing view.
Dark | Light
--- | ---
image | image

**Comment by agersant** [comment]
Sorry for the slow turnaround, I haven't had much time for Polaris recently. Code changes are all good, but I would prefer not to use the Polaris logo in this context. The grey palette is good. For reference, this is what I used for the WIP flutter client (the icon in the middle is from material icons).

image

**Comment by saecki** [comment]
> Sorry for the slow turnaround, I haven't had much time for Polaris recently.

No problem, don't feel forced to review these pull requests.

> I would prefer not to use the Polaris logo in this context.

Ok I replaced it with the same icon you used.

Since there now is a fallback artwork, I thought we shouldn't require any artwork to use the discography display mode, as it also displays the artist. Just like the flutter version.

**Pull request merged**
